change README to tell about coverage only, not full project config
sonarsource-cfamily-examples/linux-autotools-gcov-travis-sc pull request #2
Opened 2022-05-10 07:44 UTC by geoffray-adde-sonarsource

2022-05-10 10:22 UTC, arseniy-sonar requested changes

2022-05-10 10:22 UTC, arseniy-sonar commented on README.adoc
> -= Linux\Autotools
Why remove this section?

2022-05-10 10:22 UTC, arseniy-sonar commented on README.adoc
> +. Point the `sonar.coverageReportPath` property at that dedicated directory with coverage reports
```suggestion
. Point the `sonar.cfamily.gcov.reportsPath` property at that dedicated directory with coverage reports
```

2022-05-12 13:26 UTC, geoffray-adde-sonarsource commented on README.adoc
> -= Linux\Autotools
as agreed, closing this

2022-05-13 08:38 UTC, merged